# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation

    The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
    Contact: ecosystem@atlassian.com
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from atlassian_jira_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from atlassian_jira_python_sdk.api_response import AsyncGeneratorResponse
from atlassian_jira_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from atlassian_jira_python_sdk import schemas  # noqa: F401

from atlassian_jira_python_sdk.model.task_progress_bean_remove_option_from_issues_result import TaskProgressBeanRemoveOptionFromIssuesResult as TaskProgressBeanRemoveOptionFromIssuesResultSchema

from atlassian_jira_python_sdk.type.task_progress_bean_remove_option_from_issues_result import TaskProgressBeanRemoveOptionFromIssuesResult

from ...api_client import Dictionary
from atlassian_jira_python_sdk.pydantic.task_progress_bean_remove_option_from_issues_result import TaskProgressBeanRemoveOptionFromIssuesResult as TaskProgressBeanRemoveOptionFromIssuesResultPydantic

# Query params
ReplaceWithSchema = schemas.Int64Schema
JqlSchema = schemas.StrSchema
OverrideScreenSecuritySchema = schemas.BoolSchema
OverrideEditableFlagSchema = schemas.BoolSchema
RequestRequiredQueryParams = typing_extensions.TypedDict(
    'RequestRequiredQueryParams',
    {
    }
)
RequestOptionalQueryParams = typing_extensions.TypedDict(
    'RequestOptionalQueryParams',
    {
        'replaceWith': typing.Union[ReplaceWithSchema, decimal.Decimal, int, ],
        'jql': typing.Union[JqlSchema, str, ],
        'overrideScreenSecurity': typing.Union[OverrideScreenSecuritySchema, bool, ],
        'overrideEditableFlag': typing.Union[OverrideEditableFlagSchema, bool, ],
    },
    total=False
)


class RequestQueryParams(RequestRequiredQueryParams, RequestOptionalQueryParams):
    pass


request_query_replace_with = api_client.QueryParameter(
    name="replaceWith",
    style=api_client.ParameterStyle.FORM,
    schema=ReplaceWithSchema,
    explode=True,
)
request_query_jql = api_client.QueryParameter(
    name="jql",
    style=api_client.ParameterStyle.FORM,
    schema=JqlSchema,
    explode=True,
)
request_query_override_screen_security = api_client.QueryParameter(
    name="overrideScreenSecurity",
    style=api_client.ParameterStyle.FORM,
    schema=OverrideScreenSecuritySchema,
    explode=True,
)
request_query_override_editable_flag = api_client.QueryParameter(
    name="overrideEditableFlag",
    style=api_client.ParameterStyle.FORM,
    schema=OverrideEditableFlagSchema,
    explode=True,
)
# Path params
FieldKeySchema = schemas.StrSchema
OptionIdSchema = schemas.Int64Schema
RequestRequiredPathParams = typing_extensions.TypedDict(
    'RequestRequiredPathParams',
    {
        'fieldKey': typing.Union[FieldKeySchema, str, ],
        'optionId': typing.Union[OptionIdSchema, decimal.Decimal, int, ],
    }
)
RequestOptionalPathParams = typing_extensions.TypedDict(
    'RequestOptionalPathParams',
    {
    },
    total=False
)


class RequestPathParams(RequestRequiredPathParams, RequestOptionalPathParams):
    pass


request_path_field_key = api_client.PathParameter(
    name="fieldKey",
    style=api_client.ParameterStyle.SIMPLE,
    schema=FieldKeySchema,
    required=True,
)
request_path_option_id = api_client.PathParameter(
    name="optionId",
    style=api_client.ParameterStyle.SIMPLE,
    schema=OptionIdSchema,
    required=True,
)


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: schemas.Unset = schemas.unset


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: schemas.Unset = schemas.unset


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
)
SchemaFor303ResponseBodyApplicationJson = TaskProgressBeanRemoveOptionFromIssuesResultSchema


@dataclass
class ApiResponseFor303(api_client.ApiResponse):
    body: TaskProgressBeanRemoveOptionFromIssuesResult


@dataclass
class ApiResponseFor303Async(api_client.AsyncApiResponse):
    body: TaskProgressBeanRemoveOptionFromIssuesResult


_response_for_303 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor303,
    response_cls_async=ApiResponseFor303Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor303ResponseBodyApplicationJson),
    },
)


@dataclass
class ApiResponseFor400(api_client.ApiResponse):
    body: schemas.Unset = schemas.unset


@dataclass
class ApiResponseFor400Async(api_client.AsyncApiResponse):
    body: schemas.Unset = schemas.unset


_response_for_400 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor400,
    response_cls_async=ApiResponseFor400Async,
)
SchemaFor403ResponseBodyApplicationJson = schemas.StrSchema


@dataclass
class ApiResponseFor403(api_client.ApiResponse):
    body: str


@dataclass
class ApiResponseFor403Async(api_client.AsyncApiResponse):
    body: str


_response_for_403 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor403,
    response_cls_async=ApiResponseFor403Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor403ResponseBodyApplicationJson),
    },
)


@dataclass
class ApiResponseFor404(api_client.ApiResponse):
    body: schemas.Unset = schemas.unset


@dataclass
class ApiResponseFor404Async(api_client.AsyncApiResponse):
    body: schemas.Unset = schemas.unset


_response_for_404 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor404,
    response_cls_async=ApiResponseFor404Async,
)
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _deselect_option_from_issues_mapped_args(
        self,
        field_key: str,
        option_id: int,
        replace_with: typing.Optional[int] = None,
        jql: typing.Optional[str] = None,
        override_screen_security: typing.Optional[bool] = None,
        override_editable_flag: typing.Optional[bool] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _query_params = {}
        _path_params = {}
        if replace_with is not None:
            _query_params["replaceWith"] = replace_with
        if jql is not None:
            _query_params["jql"] = jql
        if override_screen_security is not None:
            _query_params["overrideScreenSecurity"] = override_screen_security
        if override_editable_flag is not None:
            _query_params["overrideEditableFlag"] = override_editable_flag
        if field_key is not None:
            _path_params["fieldKey"] = field_key
        if option_id is not None:
            _path_params["optionId"] = option_id
        args.query = _query_params
        args.path = _path_params
        return args

    async def _adeselect_option_from_issues_oapg(
        self,
            query_params: typing.Optional[dict] = {},
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Replace issue field option
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_field_key,
            request_path_option_id,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_replace_with,
            request_query_jql,
            request_query_override_screen_security,
            request_query_override_editable_flag,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'delete'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/rest/api/3/field/{fieldKey}/option/{optionId}/issue',
            auth_settings=_auth,
            headers=_headers,
        )
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            auth_settings=_auth,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _deselect_option_from_issues_oapg(
        self,
            query_params: typing.Optional[dict] = {},
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Replace issue field option
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_field_key,
            request_path_option_id,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_replace_with,
            request_query_jql,
            request_query_override_screen_security,
            request_query_override_editable_flag,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'delete'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/rest/api/3/field/{fieldKey}/option/{optionId}/issue',
            auth_settings=_auth,
            headers=_headers,
        )
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            auth_settings=_auth,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class DeselectOptionFromIssuesRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def adeselect_option_from_issues(
        self,
        field_key: str,
        option_id: int,
        replace_with: typing.Optional[int] = None,
        jql: typing.Optional[str] = None,
        override_screen_security: typing.Optional[bool] = None,
        override_editable_flag: typing.Optional[bool] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._deselect_option_from_issues_mapped_args(
            field_key=field_key,
            option_id=option_id,
            replace_with=replace_with,
            jql=jql,
            override_screen_security=override_screen_security,
            override_editable_flag=override_editable_flag,
        )
        return await self._adeselect_option_from_issues_oapg(
            query_params=args.query,
            path_params=args.path,
            **kwargs,
        )
    
    def deselect_option_from_issues(
        self,
        field_key: str,
        option_id: int,
        replace_with: typing.Optional[int] = None,
        jql: typing.Optional[str] = None,
        override_screen_security: typing.Optional[bool] = None,
        override_editable_flag: typing.Optional[bool] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._deselect_option_from_issues_mapped_args(
            field_key=field_key,
            option_id=option_id,
            replace_with=replace_with,
            jql=jql,
            override_screen_security=override_screen_security,
            override_editable_flag=override_editable_flag,
        )
        return self._deselect_option_from_issues_oapg(
            query_params=args.query,
            path_params=args.path,
        )

class DeselectOptionFromIssues(BaseApi):

    async def adeselect_option_from_issues(
        self,
        field_key: str,
        option_id: int,
        replace_with: typing.Optional[int] = None,
        jql: typing.Optional[str] = None,
        override_screen_security: typing.Optional[bool] = None,
        override_editable_flag: typing.Optional[bool] = None,
        validate: bool = False,
        **kwargs,
    ) -> None:
        raw_response = await self.raw.adeselect_option_from_issues(
            field_key=field_key,
            option_id=option_id,
            replace_with=replace_with,
            jql=jql,
            override_screen_security=override_screen_security,
            override_editable_flag=override_editable_flag,
            **kwargs,
        )
    
    
    def deselect_option_from_issues(
        self,
        field_key: str,
        option_id: int,
        replace_with: typing.Optional[int] = None,
        jql: typing.Optional[str] = None,
        override_screen_security: typing.Optional[bool] = None,
        override_editable_flag: typing.Optional[bool] = None,
        validate: bool = False,
    ) -> None:
        raw_response = self.raw.deselect_option_from_issues(
            field_key=field_key,
            option_id=option_id,
            replace_with=replace_with,
            jql=jql,
            override_screen_security=override_screen_security,
            override_editable_flag=override_editable_flag,
        )


class ApiFordelete(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def adelete(
        self,
        field_key: str,
        option_id: int,
        replace_with: typing.Optional[int] = None,
        jql: typing.Optional[str] = None,
        override_screen_security: typing.Optional[bool] = None,
        override_editable_flag: typing.Optional[bool] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._deselect_option_from_issues_mapped_args(
            field_key=field_key,
            option_id=option_id,
            replace_with=replace_with,
            jql=jql,
            override_screen_security=override_screen_security,
            override_editable_flag=override_editable_flag,
        )
        return await self._adeselect_option_from_issues_oapg(
            query_params=args.query,
            path_params=args.path,
            **kwargs,
        )
    
    def delete(
        self,
        field_key: str,
        option_id: int,
        replace_with: typing.Optional[int] = None,
        jql: typing.Optional[str] = None,
        override_screen_security: typing.Optional[bool] = None,
        override_editable_flag: typing.Optional[bool] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._deselect_option_from_issues_mapped_args(
            field_key=field_key,
            option_id=option_id,
            replace_with=replace_with,
            jql=jql,
            override_screen_security=override_screen_security,
            override_editable_flag=override_editable_flag,
        )
        return self._deselect_option_from_issues_oapg(
            query_params=args.query,
            path_params=args.path,
        )

