# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation

    The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
    Contact: ecosystem@atlassian.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredAnnouncementBannerConfigurationUpdate(TypedDict):
    pass

class OptionalAnnouncementBannerConfigurationUpdate(TypedDict, total=False):
    # Flag indicating if the announcement banner can be dismissed by the user.
    isDismissible: bool

    # Flag indicating if the announcement banner is enabled or not.
    isEnabled: bool

    # The text on the announcement banner.
    message: str

    # Visibility of the announcement banner. Can be public or private.
    visibility: str

class AnnouncementBannerConfigurationUpdate(RequiredAnnouncementBannerConfigurationUpdate, OptionalAnnouncementBannerConfigurationUpdate):
    pass
