# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation

    The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
    Contact: ecosystem@atlassian.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredAttachmentArchiveItemReadable(TypedDict):
    pass

class OptionalAttachmentArchiveItemReadable(TypedDict, total=False):
    # The position of the item within the archive.
    index: int

    # The label for the archive item.
    label: str

    # The MIME type of the archive item.
    mediaType: str

    # The path of the archive item.
    path: str

    # The size of the archive item.
    size: str

class AttachmentArchiveItemReadable(RequiredAttachmentArchiveItemReadable, OptionalAttachmentArchiveItemReadable):
    pass
