# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation

    The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
    Contact: ecosystem@atlassian.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredAvailableWorkflowForgeRule(TypedDict):
    pass

class OptionalAvailableWorkflowForgeRule(TypedDict, total=False):
    # The rule description.
    description: str

    # The unique ARI of the forge rule type.
    id: str

    # The rule name.
    name: str

    # The rule key.
    ruleKey: str

    # The rule type.
    ruleType: str

class AvailableWorkflowForgeRule(RequiredAvailableWorkflowForgeRule, OptionalAvailableWorkflowForgeRule):
    pass
