# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation

    The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
    Contact: ecosystem@atlassian.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from atlassian_jira_python_sdk.type.field_details import FieldDetails
from atlassian_jira_python_sdk.type.group_name import GroupName
from atlassian_jira_python_sdk.type.project_role import ProjectRole
from atlassian_jira_python_sdk.type.user_details import UserDetails

class RequiredEventNotification(TypedDict):
    pass

class OptionalEventNotification(TypedDict, total=False):
    # The email address.
    emailAddress: str

    # Expand options that include additional event notification details in the response.
    expand: str

    # The custom user or group field.
    field: FieldDetails

    # The specified group.
    group: GroupName

    # The ID of the notification.
    id: int

    # Identifies the recipients of the notification.
    notificationType: str

    # As a group's name can change, use of `recipient` is recommended. The identifier associated with the `notificationType` value that defines the receiver of the notification, where the receiver isn't implied by `notificationType` value. So, when `notificationType` is:   *  `User` The `parameter` is the user account ID.  *  `Group` The `parameter` is the group name.  *  `ProjectRole` The `parameter` is the project role ID.  *  `UserCustomField` The `parameter` is the ID of the custom field.  *  `GroupCustomField` The `parameter` is the ID of the custom field.
    parameter: str

    # The specified project role.
    projectRole: ProjectRole

    # The identifier associated with the `notificationType` value that defines the receiver of the notification, where the receiver isn't implied by the `notificationType` value. So, when `notificationType` is:   *  `User`, `recipient` is the user account ID.  *  `Group`, `recipient` is the group ID.  *  `ProjectRole`, `recipient` is the project role ID.  *  `UserCustomField`, `recipient` is the ID of the custom field.  *  `GroupCustomField`, `recipient` is the ID of the custom field.
    recipient: str

    # The specified user.
    user: UserDetails

class EventNotification(RequiredEventNotification, OptionalEventNotification):
    pass
