# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation

    The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
    Contact: ecosystem@atlassian.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from atlassian_jira_python_sdk.type.simplified_hierarchy_level import SimplifiedHierarchyLevel

class RequiredHierarchy(TypedDict):
    pass

class OptionalHierarchy(TypedDict, total=False):
    # The ID of the base level. This property is deprecated, see [Change notice: Removing hierarchy level IDs from next-gen APIs](https://developer.atlassian.com/cloud/jira/platform/change-notice-removing-hierarchy-level-ids-from-next-gen-apis/).
    baseLevelId: int

    # Details about the hierarchy level.
    levels: typing.List[SimplifiedHierarchyLevel]

class Hierarchy(RequiredHierarchy, OptionalHierarchy):
    pass
