# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation

    The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
    Contact: ecosystem@atlassian.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from atlassian_jira_python_sdk.type.issue_filter_for_bulk_property_set_entity_ids import IssueFilterForBulkPropertySetEntityIds

class RequiredIssueFilterForBulkPropertySet(TypedDict):
    pass

class OptionalIssueFilterForBulkPropertySet(TypedDict, total=False):
    # The value of properties to perform the bulk operation on.
    currentValue: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    entityIds: IssueFilterForBulkPropertySetEntityIds

    # Whether the bulk operation occurs only when the property is present on or absent from an issue.
    hasProperty: bool

class IssueFilterForBulkPropertySet(RequiredIssueFilterForBulkPropertySet, OptionalIssueFilterForBulkPropertySet):
    pass
