# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation

    The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
    Contact: ecosystem@atlassian.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from atlassian_jira_python_sdk.type.entity_property import EntityProperty
from atlassian_jira_python_sdk.type.history_metadata import HistoryMetadata
from atlassian_jira_python_sdk.type.issue_transition import IssueTransition
from atlassian_jira_python_sdk.type.issue_update_details_fields import IssueUpdateDetailsFields
from atlassian_jira_python_sdk.type.issue_update_details_update import IssueUpdateDetailsUpdate

class RequiredIssueUpdateDetails(TypedDict):
    pass

class OptionalIssueUpdateDetails(TypedDict, total=False):
    fields: IssueUpdateDetailsFields

    historyMetadata: HistoryMetadata

    # Details of issue properties to be add or update.
    properties: typing.List[EntityProperty]

    transition: IssueTransition

    update: IssueUpdateDetailsUpdate

class IssueUpdateDetails(RequiredIssueUpdateDetails, OptionalIssueUpdateDetails):
    pass
