# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation

    The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
    Contact: ecosystem@atlassian.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


RequiredPriority = TypedDict("RequiredPriority", {
    })

OptionalPriority = TypedDict("OptionalPriority", {
    # The description of the issue priority.
    "description": str,

    # The URL of the icon for the issue priority.
    "iconUrl": str,

    # The ID of the issue priority.
    "id": str,

    # Whether this priority is the default.
    "isDefault": bool,

    # The name of the issue priority.
    "name": str,

    # The URL of the issue priority.
    "self": str,

    # The color used to indicate the issue priority.
    "statusColor": str,
    }, total=False)

class Priority(RequiredPriority, OptionalPriority):
    pass
