# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation

    The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
    Contact: ecosystem@atlassian.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from atlassian_jira_python_sdk.type.application import Application
from atlassian_jira_python_sdk.type.remote_object import RemoteObject

class RequiredRemoteIssueLinkRequest(TypedDict):
    object: RemoteObject

class OptionalRemoteIssueLinkRequest(TypedDict, total=False):
    application: Application

    # An identifier for the remote item in the remote system. For example, the global ID for a remote item in Confluence would consist of the app ID and page ID, like this: `appId=456&pageId=123`.  Setting this field enables the remote issue link details to be updated or deleted using remote system and item details as the record identifier, rather than using the record's Jira ID.  The maximum length is 255 characters.
    globalId: str

    # Description of the relationship between the issue and the linked item. If not set, the relationship description \"links to\" is used in Jira.
    relationship: str

class RemoteIssueLinkRequest(RequiredRemoteIssueLinkRequest, OptionalRemoteIssueLinkRequest):
    pass
