# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation

    The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
    Contact: ecosystem@atlassian.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from atlassian_jira_python_sdk.type.required_mapping_by_workflows_status_ids import RequiredMappingByWorkflowsStatusIds

class RequiredRequiredMappingByWorkflows(TypedDict):
    pass

class OptionalRequiredMappingByWorkflows(TypedDict, total=False):
    # The ID of the source workflow.
    sourceWorkflowId: str

    statusIds: RequiredMappingByWorkflowsStatusIds

    # The ID of the target workflow.
    targetWorkflowId: str

class RequiredMappingByWorkflows(RequiredRequiredMappingByWorkflows, OptionalRequiredMappingByWorkflows):
    pass
