# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation

    The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
    Contact: ecosystem@atlassian.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredSuggestedIssue(TypedDict):
    pass

class OptionalSuggestedIssue(TypedDict, total=False):
    # The phrase containing the query string in HTML format, with the string highlighted with HTML bold tags.
    summary: str

    # The ID of the issue.
    id: int

    # The URL of the issue type's avatar.
    img: str

    # The key of the issue.
    key: str

    # The key of the issue in HTML format.
    keyHtml: str

    # The phrase containing the query string, as plain text.
    summaryText: str

class SuggestedIssue(RequiredSuggestedIssue, OptionalSuggestedIssue):
    pass
