# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation

    The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
    Contact: ecosystem@atlassian.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


RequiredTaskProgressBeanObject = TypedDict("RequiredTaskProgressBeanObject", {
    # The execution time of the task, in milliseconds.
    "elapsedRuntime": int,

    # The ID of the task.
    "id": str,

    # A timestamp recording when the task progress was last updated.
    "lastUpdate": int,

    # The progress of the task, as a percentage complete.
    "progress": int,

    # The URL of the task.
    "self": str,

    # The status of the task.
    "status": str,

    # A timestamp recording when the task was submitted.
    "submitted": int,

    # The ID of the user who submitted the task.
    "submittedBy": int,
    })

OptionalTaskProgressBeanObject = TypedDict("OptionalTaskProgressBeanObject", {
    # The description of the task.
    "description": str,

    # A timestamp recording when the task was finished.
    "finished": int,

    # Information about the progress of the task.
    "message": str,

    # The result of the task execution.
    "result": typing.Union[bool, date, datetime, dict, float, int, list, str, None],

    # A timestamp recording when the task was started.
    "started": int,
    }, total=False)

class TaskProgressBeanObject(RequiredTaskProgressBeanObject, OptionalTaskProgressBeanObject):
    pass
