# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation

    The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
    Contact: ecosystem@atlassian.com
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from atlassian_jira_python_sdk import schemas  # noqa: F401


class ChangedWorklogs(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    List of changed worklogs.
    """


    class MetaOapg:
        
        class properties:
            lastPage = schemas.BoolSchema
            nextPage = schemas.StrSchema
            _self = schemas.StrSchema
            since = schemas.Int64Schema
            until = schemas.Int64Schema
            
            
            class values(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['ChangedWorklog']:
                        return ChangedWorklog
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['ChangedWorklog'], typing.List['ChangedWorklog']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'values':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'ChangedWorklog':
                    return super().__getitem__(i)
            __annotations__ = {
                "lastPage": lastPage,
                "nextPage": nextPage,
                "self": _self,
                "since": since,
                "until": until,
                "values": values,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["lastPage"]) -> MetaOapg.properties.lastPage: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["nextPage"]) -> MetaOapg.properties.nextPage: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["self"]) -> MetaOapg.properties._self: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["since"]) -> MetaOapg.properties.since: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["until"]) -> MetaOapg.properties.until: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["values"]) -> MetaOapg.properties.values: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["lastPage", "nextPage", "self", "since", "until", "values", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["lastPage"]) -> typing.Union[MetaOapg.properties.lastPage, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["nextPage"]) -> typing.Union[MetaOapg.properties.nextPage, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["self"]) -> typing.Union[MetaOapg.properties._self, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["since"]) -> typing.Union[MetaOapg.properties.since, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["until"]) -> typing.Union[MetaOapg.properties.until, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["values"]) -> typing.Union[MetaOapg.properties.values, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["lastPage", "nextPage", "self", "since", "until", "values", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        lastPage: typing.Union[MetaOapg.properties.lastPage, bool, schemas.Unset] = schemas.unset,
        nextPage: typing.Union[MetaOapg.properties.nextPage, str, schemas.Unset] = schemas.unset,
        since: typing.Union[MetaOapg.properties.since, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        until: typing.Union[MetaOapg.properties.until, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        values: typing.Union[MetaOapg.properties.values, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ChangedWorklogs':
        return super().__new__(
            cls,
            *args,
            lastPage=lastPage,
            nextPage=nextPage,
            since=since,
            until=until,
            values=values,
            _configuration=_configuration,
            **kwargs,
        )

from atlassian_jira_python_sdk.model.changed_worklog import ChangedWorklog
