# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation

    The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
    Contact: ecosystem@atlassian.com
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from atlassian_jira_python_sdk import schemas  # noqa: F401


class OrderOfCustomFieldOptions(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    An ordered list of custom field option IDs and information on where to move them.
    """


    class MetaOapg:
        required = {
            "customFieldOptionIds",
        }
        
        class properties:
        
            @staticmethod
            def customFieldOptionIds() -> typing.Type['OrderOfCustomFieldOptionsCustomFieldOptionIds']:
                return OrderOfCustomFieldOptionsCustomFieldOptionIds
            after = schemas.StrSchema
            
            
            class position(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "First": "FIRST",
                        "Last": "LAST",
                    }
                
                @schemas.classproperty
                def FIRST(cls):
                    return cls("First")
                
                @schemas.classproperty
                def LAST(cls):
                    return cls("Last")
            __annotations__ = {
                "customFieldOptionIds": customFieldOptionIds,
                "after": after,
                "position": position,
            }
    
    customFieldOptionIds: 'OrderOfCustomFieldOptionsCustomFieldOptionIds'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["customFieldOptionIds"]) -> 'OrderOfCustomFieldOptionsCustomFieldOptionIds': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["after"]) -> MetaOapg.properties.after: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["position"]) -> MetaOapg.properties.position: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["customFieldOptionIds", "after", "position", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["customFieldOptionIds"]) -> 'OrderOfCustomFieldOptionsCustomFieldOptionIds': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["after"]) -> typing.Union[MetaOapg.properties.after, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["position"]) -> typing.Union[MetaOapg.properties.position, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["customFieldOptionIds", "after", "position", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        customFieldOptionIds: 'OrderOfCustomFieldOptionsCustomFieldOptionIds',
        after: typing.Union[MetaOapg.properties.after, str, schemas.Unset] = schemas.unset,
        position: typing.Union[MetaOapg.properties.position, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'OrderOfCustomFieldOptions':
        return super().__new__(
            cls,
            *args,
            customFieldOptionIds=customFieldOptionIds,
            after=after,
            position=position,
            _configuration=_configuration,
            **kwargs,
        )

from atlassian_jira_python_sdk.model.order_of_custom_field_options_custom_field_option_ids import OrderOfCustomFieldOptionsCustomFieldOptionIds
