# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation

    The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
    Contact: ecosystem@atlassian.com
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from atlassian_jira_python_sdk import schemas  # noqa: F401


class PermissionDetails(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Details for permissions of shareable entities
    """


    class MetaOapg:
        required = {
            "editPermissions",
            "sharePermissions",
        }
        
        class properties:
            
            
            class editPermissions(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['SharePermission']:
                        return SharePermission
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['SharePermission'], typing.List['SharePermission']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'editPermissions':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'SharePermission':
                    return super().__getitem__(i)
            
            
            class sharePermissions(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['SharePermission']:
                        return SharePermission
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['SharePermission'], typing.List['SharePermission']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'sharePermissions':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'SharePermission':
                    return super().__getitem__(i)
            __annotations__ = {
                "editPermissions": editPermissions,
                "sharePermissions": sharePermissions,
            }
    
    editPermissions: MetaOapg.properties.editPermissions
    sharePermissions: MetaOapg.properties.sharePermissions
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["editPermissions"]) -> MetaOapg.properties.editPermissions: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["sharePermissions"]) -> MetaOapg.properties.sharePermissions: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["editPermissions", "sharePermissions", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["editPermissions"]) -> MetaOapg.properties.editPermissions: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["sharePermissions"]) -> MetaOapg.properties.sharePermissions: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["editPermissions", "sharePermissions", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        editPermissions: typing.Union[MetaOapg.properties.editPermissions, list, tuple, ],
        sharePermissions: typing.Union[MetaOapg.properties.sharePermissions, list, tuple, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PermissionDetails':
        return super().__new__(
            cls,
            *args,
            editPermissions=editPermissions,
            sharePermissions=sharePermissions,
            _configuration=_configuration,
            **kwargs,
        )

from atlassian_jira_python_sdk.model.share_permission import SharePermission
