# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation

    The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
    Contact: ecosystem@atlassian.com
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from atlassian_jira_python_sdk import schemas  # noqa: F401


class SanitizedJqlQuery(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Details of the sanitized JQL query.
    """


    class MetaOapg:
        
        class properties:
            
            
            class accountId(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'accountId':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
        
            @staticmethod
            def errors() -> typing.Type['ErrorCollection']:
                return ErrorCollection
            initialQuery = schemas.StrSchema
            
            
            class sanitizedQuery(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'sanitizedQuery':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            __annotations__ = {
                "accountId": accountId,
                "errors": errors,
                "initialQuery": initialQuery,
                "sanitizedQuery": sanitizedQuery,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["accountId"]) -> MetaOapg.properties.accountId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["errors"]) -> 'ErrorCollection': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["initialQuery"]) -> MetaOapg.properties.initialQuery: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["sanitizedQuery"]) -> MetaOapg.properties.sanitizedQuery: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["accountId", "errors", "initialQuery", "sanitizedQuery", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["accountId"]) -> typing.Union[MetaOapg.properties.accountId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["errors"]) -> typing.Union['ErrorCollection', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["initialQuery"]) -> typing.Union[MetaOapg.properties.initialQuery, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["sanitizedQuery"]) -> typing.Union[MetaOapg.properties.sanitizedQuery, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["accountId", "errors", "initialQuery", "sanitizedQuery", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        accountId: typing.Union[MetaOapg.properties.accountId, None, str, schemas.Unset] = schemas.unset,
        errors: typing.Union['ErrorCollection', schemas.Unset] = schemas.unset,
        initialQuery: typing.Union[MetaOapg.properties.initialQuery, str, schemas.Unset] = schemas.unset,
        sanitizedQuery: typing.Union[MetaOapg.properties.sanitizedQuery, None, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'SanitizedJqlQuery':
        return super().__new__(
            cls,
            *args,
            accountId=accountId,
            errors=errors,
            initialQuery=initialQuery,
            sanitizedQuery=sanitizedQuery,
            _configuration=_configuration,
            **kwargs,
        )

from atlassian_jira_python_sdk.model.error_collection import ErrorCollection
