# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation

    The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
    Contact: ecosystem@atlassian.com
    Generated by: https://konfigthis.com
"""

from atlassian_jira_python_sdk.paths.rest_api_3_data_policy_project.get import GetDataPolicyProjects
from atlassian_jira_python_sdk.paths.rest_api_3_data_policy.get import GetDataPolicyWorkspace
from atlassian_jira_python_sdk.apis.tags.app_data_policies_eap_api_raw import AppDataPoliciesEAPApiRaw


class AppDataPoliciesEAPApi(
    GetDataPolicyProjects,
    GetDataPolicyWorkspace,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: AppDataPoliciesEAPApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = AppDataPoliciesEAPApiRaw(api_client)
