# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation

    The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
    Contact: ecosystem@atlassian.com
    Generated by: https://konfigthis.com
"""

from atlassian_jira_python_sdk.paths.rest_atlassian_connect_1_app_module_dynamic.get import GetAllRegisteredModulesRaw
from atlassian_jira_python_sdk.paths.rest_atlassian_connect_1_app_module_dynamic.post import RegisterModulesRaw
from atlassian_jira_python_sdk.paths.rest_atlassian_connect_1_app_module_dynamic.delete import RemoveRaw


class DynamicModulesApiRaw(
    GetAllRegisteredModulesRaw,
    RegisterModulesRaw,
    RemoveRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
