# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation

    The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
    Contact: ecosystem@atlassian.com
    Generated by: https://konfigthis.com
"""

from atlassian_jira_python_sdk.paths.rest_atlassian_connect_1_app_module_dynamic.get import GetAllRegisteredModules
from atlassian_jira_python_sdk.paths.rest_atlassian_connect_1_app_module_dynamic.post import RegisterModules
from atlassian_jira_python_sdk.paths.rest_atlassian_connect_1_app_module_dynamic.delete import Remove
from atlassian_jira_python_sdk.apis.tags.dynamic_modules_api_raw import DynamicModulesApiRaw


class DynamicModulesApi(
    GetAllRegisteredModules,
    RegisterModules,
    Remove,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: DynamicModulesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = DynamicModulesApiRaw(api_client)
