# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation

    The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
    Contact: ecosystem@atlassian.com
    Generated by: https://konfigthis.com
"""

from atlassian_jira_python_sdk.paths.rest_api_3_issue_issue_id_or_key_watchers.post import AddWatcherRaw
from atlassian_jira_python_sdk.paths.rest_api_3_issue_watching.post import GetWatchingIssueBulkRaw
from atlassian_jira_python_sdk.paths.rest_api_3_issue_issue_id_or_key_watchers.get import ListIssueWatchersRaw
from atlassian_jira_python_sdk.paths.rest_api_3_issue_issue_id_or_key_watchers.delete import RemoveWatcherRaw


class IssueWatchersApiRaw(
    AddWatcherRaw,
    GetWatchingIssueBulkRaw,
    ListIssueWatchersRaw,
    RemoveWatcherRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
