# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation

    The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
    Contact: ecosystem@atlassian.com
    Generated by: https://konfigthis.com
"""

from atlassian_jira_python_sdk.paths.rest_api_3_issuetype.post import CreateIssueType
from atlassian_jira_python_sdk.paths.rest_api_3_issuetype_id.delete import DeleteById
from atlassian_jira_python_sdk.paths.rest_api_3_issuetype.get import GetAllForUser
from atlassian_jira_python_sdk.paths.rest_api_3_issuetype_id.get import GetById
from atlassian_jira_python_sdk.paths.rest_api_3_issuetype_project.get import GetProjectIssueTypes
from atlassian_jira_python_sdk.paths.rest_api_3_issuetype_id_alternatives.get import ListAlternativeIssueTypes
from atlassian_jira_python_sdk.paths.rest_api_3_issuetype_id_avatar2.post import LoadIssueTypeAvatar
from atlassian_jira_python_sdk.paths.rest_api_3_issuetype_id.put import UpdateIssueType
from atlassian_jira_python_sdk.apis.tags.issue_types_api_raw import IssueTypesApiRaw


class IssueTypesApi(
    CreateIssueType,
    DeleteById,
    GetAllForUser,
    GetById,
    GetProjectIssueTypes,
    ListAlternativeIssueTypes,
    LoadIssueTypeAvatar,
    UpdateIssueType,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: IssueTypesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = IssueTypesApiRaw(api_client)
