# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation

    The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
    Contact: ecosystem@atlassian.com
    Generated by: https://konfigthis.com
"""

from atlassian_jira_python_sdk.paths.rest_api_3_jql_pdcleaner.post import ConvertUserIdentifiersToAccountIdsInJqlQueries
from atlassian_jira_python_sdk.paths.rest_api_3_jql_autocompletedata_suggestions.get import GetFieldAutoCompleteForQueryString
from atlassian_jira_python_sdk.paths.rest_api_3_jql_autocompletedata.get import GetFieldReferenceData
from atlassian_jira_python_sdk.paths.rest_api_3_jql_autocompletedata.post import GetFieldReferenceDataPost
from atlassian_jira_python_sdk.paths.rest_api_3_jql_parse.post import ParseAndValidate
from atlassian_jira_python_sdk.paths.rest_api_3_jql_sanitize.post import SanitizeJqlQueries
from atlassian_jira_python_sdk.apis.tags.jql_api_raw import JQLApiRaw


class JQLApi(
    ConvertUserIdentifiersToAccountIdsInJqlQueries,
    GetFieldAutoCompleteForQueryString,
    GetFieldReferenceData,
    GetFieldReferenceDataPost,
    ParseAndValidate,
    SanitizeJqlQueries,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: JQLApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = JQLApiRaw(api_client)
