# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation

    The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
    Contact: ecosystem@atlassian.com
    Generated by: https://konfigthis.com
"""

from atlassian_jira_python_sdk.paths.rest_api_3_projectvalidate_valid_project_key.get import GenerateValidKey
from atlassian_jira_python_sdk.paths.rest_api_3_projectvalidate_valid_project_name.get import GetValidProjectName
from atlassian_jira_python_sdk.paths.rest_api_3_projectvalidate_key.get import ValidateKeyString
from atlassian_jira_python_sdk.apis.tags.project_key_and_name_validation_api_raw import ProjectKeyAndNameValidationApiRaw


class ProjectKeyAndNameValidationApi(
    GenerateValidKey,
    GetValidProjectName,
    ValidateKeyString,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ProjectKeyAndNameValidationApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ProjectKeyAndNameValidationApiRaw(api_client)
