# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation

    The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
    Contact: ecosystem@atlassian.com
    Generated by: https://konfigthis.com
"""

from atlassian_jira_python_sdk.paths.rest_api_3_workflowscheme_project.put import AssignToProject
from atlassian_jira_python_sdk.paths.rest_api_3_workflowscheme_project.get import ListProjectAssociations
from atlassian_jira_python_sdk.apis.tags.workflow_scheme_project_associations_api_raw import WorkflowSchemeProjectAssociationsApiRaw


class WorkflowSchemeProjectAssociationsApi(
    AssignToProject,
    ListProjectAssociations,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: WorkflowSchemeProjectAssociationsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = WorkflowSchemeProjectAssociationsApiRaw(api_client)
