# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation

    The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
    Contact: ecosystem@atlassian.com
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from atlassian_jira_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from atlassian_jira_python_sdk.api_response import AsyncGeneratorResponse
from atlassian_jira_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from atlassian_jira_python_sdk import schemas  # noqa: F401

from atlassian_jira_python_sdk.model.error_collection import ErrorCollection as ErrorCollectionSchema
from atlassian_jira_python_sdk.model.page_bean_workflow import PageBeanWorkflow as PageBeanWorkflowSchema

from atlassian_jira_python_sdk.type.page_bean_workflow import PageBeanWorkflow
from atlassian_jira_python_sdk.type.error_collection import ErrorCollection

from ...api_client import Dictionary
from atlassian_jira_python_sdk.pydantic.page_bean_workflow import PageBeanWorkflow as PageBeanWorkflowPydantic
from atlassian_jira_python_sdk.pydantic.error_collection import ErrorCollection as ErrorCollectionPydantic

from . import path

# Query params
StartAtSchema = schemas.Int64Schema
MaxResultsSchema = schemas.Int32Schema


class WorkflowNameSchema(
    schemas.ListSchema
):


    class MetaOapg:
        unique_items = True
        items = schemas.StrSchema

    def __new__(
        cls,
        arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, str, ]], typing.List[typing.Union[MetaOapg.items, str, ]]],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'WorkflowNameSchema':
        return super().__new__(
            cls,
            arg,
            _configuration=_configuration,
        )

    def __getitem__(self, i: int) -> MetaOapg.items:
        return super().__getitem__(i)
ExpandSchema = schemas.StrSchema
QueryStringSchema = schemas.StrSchema


class OrderBySchema(
    schemas.EnumBase,
    schemas.StrSchema
):


    class MetaOapg:
        enum_value_to_name = {
            "name": "NAME",
            "-name": "NAME",
            "+name": "NAME",
            "created": "CREATED",
            "-created": "CREATED",
            "+created": "CREATED",
            "updated": "UPDATED",
            "+updated": "UPDATED",
            "-updated": "UPDATED",
        }
    
    @schemas.classproperty
    def NAME(cls):
        return cls("name")
    
    @schemas.classproperty
    def NAME(cls):
        return cls("-name")
    
    @schemas.classproperty
    def NAME(cls):
        return cls("+name")
    
    @schemas.classproperty
    def CREATED(cls):
        return cls("created")
    
    @schemas.classproperty
    def CREATED(cls):
        return cls("-created")
    
    @schemas.classproperty
    def CREATED(cls):
        return cls("+created")
    
    @schemas.classproperty
    def UPDATED(cls):
        return cls("updated")
    
    @schemas.classproperty
    def UPDATED(cls):
        return cls("+updated")
    
    @schemas.classproperty
    def UPDATED(cls):
        return cls("-updated")
IsActiveSchema = schemas.BoolSchema
RequestRequiredQueryParams = typing_extensions.TypedDict(
    'RequestRequiredQueryParams',
    {
    }
)
RequestOptionalQueryParams = typing_extensions.TypedDict(
    'RequestOptionalQueryParams',
    {
        'startAt': typing.Union[StartAtSchema, decimal.Decimal, int, ],
        'maxResults': typing.Union[MaxResultsSchema, decimal.Decimal, int, ],
        'workflowName': typing.Union[WorkflowNameSchema, list, tuple, ],
        'expand': typing.Union[ExpandSchema, str, ],
        'queryString': typing.Union[QueryStringSchema, str, ],
        'orderBy': typing.Union[OrderBySchema, str, ],
        'isActive': typing.Union[IsActiveSchema, bool, ],
    },
    total=False
)


class RequestQueryParams(RequestRequiredQueryParams, RequestOptionalQueryParams):
    pass


request_query_start_at = api_client.QueryParameter(
    name="startAt",
    style=api_client.ParameterStyle.FORM,
    schema=StartAtSchema,
    explode=True,
)
request_query_max_results = api_client.QueryParameter(
    name="maxResults",
    style=api_client.ParameterStyle.FORM,
    schema=MaxResultsSchema,
    explode=True,
)
request_query_workflow_name = api_client.QueryParameter(
    name="workflowName",
    style=api_client.ParameterStyle.FORM,
    schema=WorkflowNameSchema,
    explode=True,
)
request_query_expand = api_client.QueryParameter(
    name="expand",
    style=api_client.ParameterStyle.FORM,
    schema=ExpandSchema,
    explode=True,
)
request_query_query_string = api_client.QueryParameter(
    name="queryString",
    style=api_client.ParameterStyle.FORM,
    schema=QueryStringSchema,
    explode=True,
)
request_query_order_by = api_client.QueryParameter(
    name="orderBy",
    style=api_client.ParameterStyle.FORM,
    schema=OrderBySchema,
    explode=True,
)
request_query_is_active = api_client.QueryParameter(
    name="isActive",
    style=api_client.ParameterStyle.FORM,
    schema=IsActiveSchema,
    explode=True,
)
_auth = [
    'OAuth2',
    'basicAuth',
]
SchemaFor200ResponseBodyApplicationJson = PageBeanWorkflowSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: PageBeanWorkflow


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: PageBeanWorkflow


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
    },
)


@dataclass
class ApiResponseFor401(api_client.ApiResponse):
    body: schemas.Unset = schemas.unset


@dataclass
class ApiResponseFor401Async(api_client.AsyncApiResponse):
    body: schemas.Unset = schemas.unset


_response_for_401 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor401,
    response_cls_async=ApiResponseFor401Async,
)
SchemaFor403ResponseBodyApplicationJson = ErrorCollectionSchema


@dataclass
class ApiResponseFor403(api_client.ApiResponse):
    body: ErrorCollection


@dataclass
class ApiResponseFor403Async(api_client.AsyncApiResponse):
    body: ErrorCollection


_response_for_403 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor403,
    response_cls_async=ApiResponseFor403Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor403ResponseBodyApplicationJson),
    },
)
_status_code_to_response = {
    '200': _response_for_200,
    '401': _response_for_401,
    '403': _response_for_403,
}
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _get_paginated_workflow_mapped_args(
        self,
        start_at: typing.Optional[int] = None,
        max_results: typing.Optional[int] = None,
        workflow_name: typing.Optional[typing.List[str]] = None,
        expand: typing.Optional[str] = None,
        query_string: typing.Optional[str] = None,
        order_by: typing.Optional[str] = None,
        is_active: typing.Optional[bool] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _query_params = {}
        if start_at is not None:
            _query_params["startAt"] = start_at
        if max_results is not None:
            _query_params["maxResults"] = max_results
        if workflow_name is not None:
            _query_params["workflowName"] = workflow_name
        if expand is not None:
            _query_params["expand"] = expand
        if query_string is not None:
            _query_params["queryString"] = query_string
        if order_by is not None:
            _query_params["orderBy"] = order_by
        if is_active is not None:
            _query_params["isActive"] = is_active
        args.query = _query_params
        return args

    async def _aget_paginated_workflow_oapg(
        self,
            query_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Get workflows paginated
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        used_path = path.value
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_start_at,
            request_query_max_results,
            request_query_workflow_name,
            request_query_expand,
            request_query_query_string,
            request_query_order_by,
            request_query_is_active,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/rest/api/3/workflow/search',
            auth_settings=_auth,
            headers=_headers,
        )
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            auth_settings=_auth,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _get_paginated_workflow_oapg(
        self,
            query_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Get workflows paginated
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        used_path = path.value
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_start_at,
            request_query_max_results,
            request_query_workflow_name,
            request_query_expand,
            request_query_query_string,
            request_query_order_by,
            request_query_is_active,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/rest/api/3/workflow/search',
            auth_settings=_auth,
            headers=_headers,
        )
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            auth_settings=_auth,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class GetPaginatedWorkflowRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def aget_paginated_workflow(
        self,
        start_at: typing.Optional[int] = None,
        max_results: typing.Optional[int] = None,
        workflow_name: typing.Optional[typing.List[str]] = None,
        expand: typing.Optional[str] = None,
        query_string: typing.Optional[str] = None,
        order_by: typing.Optional[str] = None,
        is_active: typing.Optional[bool] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._get_paginated_workflow_mapped_args(
            start_at=start_at,
            max_results=max_results,
            workflow_name=workflow_name,
            expand=expand,
            query_string=query_string,
            order_by=order_by,
            is_active=is_active,
        )
        return await self._aget_paginated_workflow_oapg(
            query_params=args.query,
            **kwargs,
        )
    
    def get_paginated_workflow(
        self,
        start_at: typing.Optional[int] = None,
        max_results: typing.Optional[int] = None,
        workflow_name: typing.Optional[typing.List[str]] = None,
        expand: typing.Optional[str] = None,
        query_string: typing.Optional[str] = None,
        order_by: typing.Optional[str] = None,
        is_active: typing.Optional[bool] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._get_paginated_workflow_mapped_args(
            start_at=start_at,
            max_results=max_results,
            workflow_name=workflow_name,
            expand=expand,
            query_string=query_string,
            order_by=order_by,
            is_active=is_active,
        )
        return self._get_paginated_workflow_oapg(
            query_params=args.query,
        )

class GetPaginatedWorkflow(BaseApi):

    async def aget_paginated_workflow(
        self,
        start_at: typing.Optional[int] = None,
        max_results: typing.Optional[int] = None,
        workflow_name: typing.Optional[typing.List[str]] = None,
        expand: typing.Optional[str] = None,
        query_string: typing.Optional[str] = None,
        order_by: typing.Optional[str] = None,
        is_active: typing.Optional[bool] = None,
        validate: bool = False,
        **kwargs,
    ) -> PageBeanWorkflowPydantic:
        raw_response = await self.raw.aget_paginated_workflow(
            start_at=start_at,
            max_results=max_results,
            workflow_name=workflow_name,
            expand=expand,
            query_string=query_string,
            order_by=order_by,
            is_active=is_active,
            **kwargs,
        )
        if validate:
            return PageBeanWorkflowPydantic(**raw_response.body)
        return api_client.construct_model_instance(PageBeanWorkflowPydantic, raw_response.body)
    
    
    def get_paginated_workflow(
        self,
        start_at: typing.Optional[int] = None,
        max_results: typing.Optional[int] = None,
        workflow_name: typing.Optional[typing.List[str]] = None,
        expand: typing.Optional[str] = None,
        query_string: typing.Optional[str] = None,
        order_by: typing.Optional[str] = None,
        is_active: typing.Optional[bool] = None,
        validate: bool = False,
    ) -> PageBeanWorkflowPydantic:
        raw_response = self.raw.get_paginated_workflow(
            start_at=start_at,
            max_results=max_results,
            workflow_name=workflow_name,
            expand=expand,
            query_string=query_string,
            order_by=order_by,
            is_active=is_active,
        )
        if validate:
            return PageBeanWorkflowPydantic(**raw_response.body)
        return api_client.construct_model_instance(PageBeanWorkflowPydantic, raw_response.body)


class ApiForget(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def aget(
        self,
        start_at: typing.Optional[int] = None,
        max_results: typing.Optional[int] = None,
        workflow_name: typing.Optional[typing.List[str]] = None,
        expand: typing.Optional[str] = None,
        query_string: typing.Optional[str] = None,
        order_by: typing.Optional[str] = None,
        is_active: typing.Optional[bool] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._get_paginated_workflow_mapped_args(
            start_at=start_at,
            max_results=max_results,
            workflow_name=workflow_name,
            expand=expand,
            query_string=query_string,
            order_by=order_by,
            is_active=is_active,
        )
        return await self._aget_paginated_workflow_oapg(
            query_params=args.query,
            **kwargs,
        )
    
    def get(
        self,
        start_at: typing.Optional[int] = None,
        max_results: typing.Optional[int] = None,
        workflow_name: typing.Optional[typing.List[str]] = None,
        expand: typing.Optional[str] = None,
        query_string: typing.Optional[str] = None,
        order_by: typing.Optional[str] = None,
        is_active: typing.Optional[bool] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._get_paginated_workflow_mapped_args(
            start_at=start_at,
            max_results=max_results,
            workflow_name=workflow_name,
            expand=expand,
            query_string=query_string,
            order_by=order_by,
            is_active=is_active,
        )
        return self._get_paginated_workflow_oapg(
            query_params=args.query,
        )

