# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation

    The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
    Contact: ecosystem@atlassian.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from atlassian_jira_python_sdk.pydantic.entity_property import EntityProperty
from atlassian_jira_python_sdk.pydantic.user_details import UserDetails
from atlassian_jira_python_sdk.pydantic.visibility import Visibility

class Comment(BaseModel):
    author: typing.Optional[UserDetails] = Field(None, alias='author')

    # The comment text in [Atlassian Document Format](https://developer.atlassian.com/cloud/jira/platform/apis/document/structure/).
    body: typing.Optional[typing.Union[bool, date, datetime, dict, float, int, list, str, None]] = Field(None, alias='body')

    # The date and time at which the comment was created.
    created: typing.Optional[datetime] = Field(None, alias='created')

    # The ID of the comment.
    id: typing.Optional[str] = Field(None, alias='id')

    # Whether the comment was added from an email sent by a person who is not part of the issue. See [Allow external emails to be added as comments on issues](https://support.atlassian.com/jira-service-management-cloud/docs/allow-external-emails-to-be-added-as-comments-on-issues/)for information on setting up this feature.
    jsd_author_can_see_request: typing.Optional[bool] = Field(None, alias='jsdAuthorCanSeeRequest')

    # Whether the comment is visible in Jira Service Desk. Defaults to true when comments are created in the Jira Cloud Platform. This includes when the site doesn't use Jira Service Desk or the project isn't a Jira Service Desk project and, therefore, there is no Jira Service Desk for the issue to be visible on. To create a comment with its visibility in Jira Service Desk set to false, use the Jira Service Desk REST API [Create request comment](https://developer.atlassian.com/cloud/jira/service-desk/rest/#api-rest-servicedeskapi-request-issueIdOrKey-comment-post) operation.
    jsd_public: typing.Optional[bool] = Field(None, alias='jsdPublic')

    # A list of comment properties. Optional on create and update.
    properties: typing.Optional[typing.List[EntityProperty]] = Field(None, alias='properties')

    # The rendered version of the comment.
    rendered_body: typing.Optional[str] = Field(None, alias='renderedBody')

    # The URL of the comment.
    self_: typing.Optional[str] = Field(None, alias='self')

    update_author: typing.Optional[UserDetails] = Field(None, alias='updateAuthor')

    # The date and time at which the comment was updated last.
    updated: typing.Optional[datetime] = Field(None, alias='updated')

    visibility: typing.Optional[Visibility] = Field(None, alias='visibility')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
