# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation

    The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
    Contact: ecosystem@atlassian.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from atlassian_jira_python_sdk.pydantic.rule_configuration import RuleConfiguration
from atlassian_jira_python_sdk.pydantic.workflow_transition import WorkflowTransition

class ConnectWorkflowTransitionRule(BaseModel):
    configuration: RuleConfiguration = Field(alias='configuration')

    # The ID of the transition rule.
    id: str = Field(alias='id')

    # The key of the rule, as defined in the Connect app descriptor.
    key: str = Field(alias='key')

    transition: typing.Optional[WorkflowTransition] = Field(None, alias='transition')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
