# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation

    The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
    Contact: ecosystem@atlassian.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from atlassian_jira_python_sdk.pydantic.custom_field_context_default_value_multiple_option_option_ids import CustomFieldContextDefaultValueMultipleOptionOptionIds

class CustomFieldContextDefaultValueMultipleOption(BaseModel):
    # The ID of the context.
    context_id: str = Field(alias='contextId')

    option_ids: CustomFieldContextDefaultValueMultipleOptionOptionIds = Field(alias='optionIds')

    type: str = Field(alias='type')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
