# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation

    The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
    Contact: ecosystem@atlassian.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from atlassian_jira_python_sdk.pydantic.issue_type_screen_scheme_mapping import IssueTypeScreenSchemeMapping

class IssueTypeScreenSchemeDetails(BaseModel):
    # The IDs of the screen schemes for the issue type IDs and *default*. A *default* entry is required to create an issue type screen scheme, it defines the mapping for all issue types without a screen scheme.
    issue_type_mappings: typing.List[IssueTypeScreenSchemeMapping] = Field(alias='issueTypeMappings')

    # The name of the issue type screen scheme. The name must be unique. The maximum length is 255 characters.
    name: str = Field(alias='name')

    # The description of the issue type screen scheme. The maximum length is 255 characters.
    description: typing.Optional[str] = Field(None, alias='description')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
