# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation

    The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
    Contact: ecosystem@atlassian.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from atlassian_jira_python_sdk.pydantic.project_component_metadata import ProjectComponentMetadata
from atlassian_jira_python_sdk.pydantic.user import User

class ProjectComponent(BaseModel):
    # The description for the component. Optional when creating or updating a component.
    description: typing.Optional[str] = Field(None, alias='description')

    # Compass component's ID. Can't be updated. Not required for creating a Project Component.
    ari: typing.Optional[str] = Field(None, alias='ari')

    # The details of the user associated with `assigneeType`, if any. See `realAssignee` for details of the user assigned to issues created with this component.
    assignee: typing.Optional[User] = Field(None, alias='assignee')

    # The nominal user type used to determine the assignee for issues created with this component. See `realAssigneeType` for details on how the type of the user, and hence the user, assigned to issues is determined. Can take the following values:   *  `PROJECT_LEAD` the assignee to any issues created with this component is nominally the lead for the project the component is in.  *  `COMPONENT_LEAD` the assignee to any issues created with this component is nominally the lead for the component.  *  `UNASSIGNED` an assignee is not set for issues created with this component.  *  `PROJECT_DEFAULT` the assignee to any issues created with this component is nominally the default assignee for the project that the component is in.  Default value: `PROJECT_DEFAULT`.   Optional when creating or updating a component.
    assignee_type: typing.Optional[Literal["PROJECT_DEFAULT", "COMPONENT_LEAD", "PROJECT_LEAD", "UNASSIGNED"]] = Field(None, alias='assigneeType')

    # The unique identifier for the component.
    id: typing.Optional[str] = Field(None, alias='id')

    # Whether a user is associated with `assigneeType`. For example, if the `assigneeType` is set to `COMPONENT_LEAD` but the component lead is not set, then `false` is returned.
    is_assignee_type_valid: typing.Optional[bool] = Field(None, alias='isAssigneeTypeValid')

    # The user details for the component's lead user.
    lead: typing.Optional[User] = Field(None, alias='lead')

    # The accountId of the component's lead user. The accountId uniquely identifies the user across all Atlassian products. For example, *5b10ac8d82e05b22cc7d4ef5*.
    lead_account_id: typing.Optional[str] = Field(None, alias='leadAccountId')

    # This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details.
    lead_user_name: typing.Optional[str] = Field(None, alias='leadUserName')

    metadata: typing.Optional[ProjectComponentMetadata] = Field(None, alias='metadata')

    # The unique name for the component in the project. Required when creating a component. Optional when updating a component. The maximum length is 255 characters.
    name: typing.Optional[str] = Field(None, alias='name')

    # The key of the project the component is assigned to. Required when creating a component. Can't be updated.
    project: typing.Optional[str] = Field(None, alias='project')

    # The ID of the project the component is assigned to.
    project_id: typing.Optional[int] = Field(None, alias='projectId')

    # The user assigned to issues created with this component, when `assigneeType` does not identify a valid assignee.
    real_assignee: typing.Optional[User] = Field(None, alias='realAssignee')

    # The type of the assignee that is assigned to issues created with this component, when an assignee cannot be set from the `assigneeType`. For example, `assigneeType` is set to `COMPONENT_LEAD` but no component lead is set. This property is set to one of the following values:   *  `PROJECT_LEAD` when `assigneeType` is `PROJECT_LEAD` and the project lead has permission to be assigned issues in the project that the component is in.  *  `COMPONENT_LEAD` when `assignee`Type is `COMPONENT_LEAD` and the component lead has permission to be assigned issues in the project that the component is in.  *  `UNASSIGNED` when `assigneeType` is `UNASSIGNED` and Jira is configured to allow unassigned issues.  *  `PROJECT_DEFAULT` when none of the preceding cases are true.
    real_assignee_type: typing.Optional[Literal["PROJECT_DEFAULT", "COMPONENT_LEAD", "PROJECT_LEAD", "UNASSIGNED"]] = Field(None, alias='realAssigneeType')

    # The URL of the component.
    self_: typing.Optional[str] = Field(None, alias='self')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
