# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation

    The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
    Contact: ecosystem@atlassian.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from atlassian_jira_python_sdk.pydantic.application import Application
from atlassian_jira_python_sdk.pydantic.remote_object import RemoteObject

class RemoteIssueLink(BaseModel):
    # Details of the remote application the linked item is in.
    application: typing.Optional[Application] = Field(None, alias='application')

    # The global ID of the link, such as the ID of the item on the remote system.
    global_id: typing.Optional[str] = Field(None, alias='globalId')

    # The ID of the link.
    id: typing.Optional[int] = Field(None, alias='id')

    # Details of the item linked to.
    object: typing.Optional[RemoteObject] = Field(None, alias='object')

    # Description of the relationship between the issue and the linked item.
    relationship: typing.Optional[str] = Field(None, alias='relationship')

    # The URL of the link.
    self_: typing.Optional[str] = Field(None, alias='self')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
