# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation

    The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
    Contact: ecosystem@atlassian.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class Resolution(BaseModel):
    # The description of the issue resolution.
    description: typing.Optional[str] = Field(None, alias='description')

    # The ID of the issue resolution.
    id: typing.Optional[str] = Field(None, alias='id')

    # The name of the issue resolution.
    name: typing.Optional[str] = Field(None, alias='name')

    # The URL of the issue resolution.
    self_: typing.Optional[str] = Field(None, alias='self')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
