# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation

    The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
    Contact: ecosystem@atlassian.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from atlassian_jira_python_sdk.pydantic.avatar_urls_bean import AvatarUrlsBean
from atlassian_jira_python_sdk.pydantic.simple_list_wrapper_application_role import SimpleListWrapperApplicationRole
from atlassian_jira_python_sdk.pydantic.simple_list_wrapper_group_name import SimpleListWrapperGroupName

class User(BaseModel):
    # The account ID of the user, which uniquely identifies the user across all Atlassian products. For example, *5b10ac8d82e05b22cc7d4ef5*. Required in requests.
    account_id: typing.Optional[str] = Field(None, alias='accountId')

    # The user account type. Can take the following values:   *  `atlassian` regular Atlassian user account  *  `app` system account used for Connect applications and OAuth to represent external systems  *  `customer` Jira Service Desk account representing an external service desk
    account_type: typing.Optional[Literal["atlassian", "app", "customer", "unknown"]] = Field(None, alias='accountType')

    # Whether the user is active.
    active: typing.Optional[bool] = Field(None, alias='active')

    # The application roles the user is assigned to.
    application_roles: typing.Optional[SimpleListWrapperApplicationRole] = Field(None, alias='applicationRoles')

    # The avatars of the user.
    avatar_urls: typing.Optional[AvatarUrlsBean] = Field(None, alias='avatarUrls')

    # The display name of the user. Depending on the user’s privacy setting, this may return an alternative value.
    display_name: typing.Optional[str] = Field(None, alias='displayName')

    # The email address of the user. Depending on the user’s privacy setting, this may be returned as null.
    email_address: typing.Optional[str] = Field(None, alias='emailAddress')

    # Expand options that include additional user details in the response.
    expand: typing.Optional[str] = Field(None, alias='expand')

    # The groups that the user belongs to.
    groups: typing.Optional[SimpleListWrapperGroupName] = Field(None, alias='groups')

    # This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details.
    key: typing.Optional[str] = Field(None, alias='key')

    # The locale of the user. Depending on the user’s privacy setting, this may be returned as null.
    locale: typing.Optional[str] = Field(None, alias='locale')

    # This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details.
    name: typing.Optional[str] = Field(None, alias='name')

    # The URL of the user.
    self_: typing.Optional[str] = Field(None, alias='self')

    # The time zone specified in the user's profile. Depending on the user’s privacy setting, this may be returned as null.
    time_zone: typing.Optional[str] = Field(None, alias='timeZone')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
