# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation

    The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
    Contact: ecosystem@atlassian.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from atlassian_jira_python_sdk.pydantic.project_and_issue_type_pair import ProjectAndIssueTypePair

class WorkflowElementReference(BaseModel):
    # A property key.
    property_key: typing.Optional[str] = Field(None, alias='propertyKey')

    # A rule ID.
    rule_id: typing.Optional[str] = Field(None, alias='ruleId')

    status_mapping_reference: typing.Optional[ProjectAndIssueTypePair] = Field(None, alias='statusMappingReference')

    # A status reference.
    status_reference: typing.Optional[str] = Field(None, alias='statusReference')

    # A transition ID.
    transition_id: typing.Optional[str] = Field(None, alias='transitionId')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
