from atlassian_jira_python_sdk.paths.rest_api_3_dashboard_dashboard_id_items_item_id_properties_property_key.get import ApiForget
from atlassian_jira_python_sdk.paths.rest_api_3_dashboard_dashboard_id_items_item_id_properties_property_key.put import ApiForput
from atlassian_jira_python_sdk.paths.rest_api_3_dashboard_dashboard_id_items_item_id_properties_property_key.delete import ApiFordelete


class RestApi3DashboardDashboardIdItemsItemIdPropertiesPropertyKey(
    ApiForget,
    ApiForput,
    ApiFordelete,
):
    pass
